### ISSUE TITLE
Distributivity of Stack and Compose

### ISSUE THREAD

**Issue by caldwellb** [inQWIRE/VyZX#3]
It Doesn't Matter Which Way You Slice It (within reason).

ZX_semantics Compose (Stack A B) (Stack C D) = ZX_semantics Stack (Compose A C) Compose (B D)

as long as dimensions work. Will be added to ZX.v

**Comment by adrianleh** [comment]
Stealing the assignment, since I need this lemma

**Comment by adrianleh** [comment]
Done
